import React from 'react';
import Modal from '../Modal/Modal';
import Button from '../Button/Button';
import Alert from '../Alert/Alert';
import Spinner from '../Spinner/Spinner';

function AiDraftModal({ isOpen, onClose, onUseDraft, draftText, loading }) {
  const footer = (
    <>
      <Button variant="ghost" onClick={onClose}>Cancel</Button>
      <Button variant="primary" disabled={loading || !draftText} onClick={() => onUseDraft?.(draftText)}>
        Use This Draft &rarr;
      </Button>
    </>
  );

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="AI-Generated Memo Draft"
      subtitle="Review the AI-generated adjudicative memo"
      size="lg"
      footer={footer}
    >
      <Alert variant="amber" icon="!" title="Human Review Required">
        This draft was generated by AI and requires human review. All sections marked
        <strong> [ADJUDICATOR INPUT REQUIRED] </strong>
        must be completed by the adjudicator before submission.
      </Alert>

      <div style={{
        background: 'var(--surface, #f9fafb)',
        border: '1px solid var(--border, #e5e7eb)',
        borderRadius: '8px',
        padding: '20px',
        marginTop: '12px',
        maxHeight: '400px',
        overflow: 'auto',
        fontFamily: 'var(--font-mono, "JetBrains Mono", monospace)',
        fontSize: '13px',
        lineHeight: '1.6',
        whiteSpace: 'pre-wrap',
      }}>
        {loading ? (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '12px', padding: '40px 0' }}>
            <Spinner size="md" />
            <span style={{ color: 'var(--ink-light, #6b7280)', fontSize: '14px' }}>Generating memo draft...</span>
          </div>
        ) : (
          draftText || 'No draft available.'
        )}
      </div>
    </Modal>
  );
}

export default AiDraftModal;
